### ISSUE TITLE
User Branch causes fatal error

### ISSUE THREAD

**Issue by Serray** [turnermm/toolbuttondel#14]
Hey,

i tried to install the user branch for this plugin,
to remove the toolbox and the file manager for non-registered users.

If i install the plugin via plugin manager i get the following error and need to delete the plugin to get the wiki back to work.

Fatal error: Uncaught ArgumentCountError: Too few arguments to function metaFN(), 1 passed in E:\xampp\htdocs\dokuwiki\lib\plugins\toolbuttondel\action.php on line 26 and exactly 2 expected in E:\xampp\htdocs\dokuwiki\inc\pageutils.php:351 Stack trace: #0 E:\xampp\htdocs\dokuwiki\lib\plugins\toolbuttondel\action.php(26): metaFN('toolbuttondel:c...') #1 E:\xampp\htdocs\dokuwiki\inc\Extension\EventHandler.php(81): action_plugin_toolbuttondel->_started(Object(dokuwiki\Extension\Event), Array) #2 E:\xampp\htdocs\dokuwiki\inc\Extension\Event.php(72): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE') #3 E:\xampp\htdocs\dokuwiki\inc\Extension\Event.php(128): dokuwiki\Extension\Event->advise_before(false) #4 E:\xampp\htdocs\dokuwiki\inc\Extension\Event.php(195): dokuwiki\Extension\Event->trigger(NULL, false) #5 E:\xampp\htdocs\dokuwiki\doku.php(116): dokuwiki\Extension\Event::createAndTrigger('DOKUWIKI_STARTE...', Array) #6 {main} thrown in E:\xampp\htdocs\dokuwiki\inc\pageutils.php on line 351

**Comment by turnermm** [comment]
Should be fixed

**Comment by turnermm** [comment]
Fixed
